seed:
defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

wandb:
  project: "optimize_barlow_resnet34_nomodify_noskips"

method: "barlow_twins"

# name: "vgg19_bn_3" # change here for cifar100
# backbone:
#   name: "vgg19_bn"


name: "resnet34"
backbone:
  name: "resnet_custom"
  modify_to_cifar: False
  kwargs:
    model_config:
      backbone_type: "resnet34"
      batchnorm_layers: True
      width_scale: 1
      skips: False

  
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  scale_loss: 0.01
  projector:
data:
  dataset: cifar10 # change here for cifar100
  train_path: "./datasets"
  val_path: "./datasets"
  format: "image_folder"
  num_workers: 14
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
checkpoint:
  enabled: False
  dir: "trained_models_test"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 50
# overfit_batches: 10

# gpu
scheduler:
  name: "warmup_cosine"
sync_batchnorm: True
devices: [0]
accelerator: "gpu"
strategy: "auto"
num_sanity_val_steps: 0
precision: 16

# cpu
# scheduler:
#   name: "none"
# sync_batchnorm: False
# devices: 1
# accelerator: "cpu"
# strategy: "ddp"
# precision: "32-true"